### PR TITLE
export cacheElementEventHandlers

### PR DESCRIPTION
**Pull request by ahdinosaur**
hey, this is a cool module!

i wrote a really minimal hyperscript-style module that wraps well with this module: [`hyps`](https://github.com/ahdinosaur/hyps).

then in pursuit of a full [`yo-yo`](https://github.com/maxogden/yo-yo/), i wrote the following code to wrap [`morphdom`](https://github.com/patrick-steele-idem/morphdom), to provide event handler morphing, which needs this pull request to work.

note: i don't actually understand ES modules (prefer `require` and `module.exports`) so i assume that's how i export `cacheElementEventHandlers`? to write the below i just changed the compiled `val` code.

```js
const morphdom = require('morphdom')
const Val = require('@skatejs/val')

module.exports = function update (fromNode, toNode, opts = {}) {
  if (!opts.onBeforeElUpdated) opts.onBeforeElUpdated = copyEvents

  return morphdom(fromNode, toNode, opts)
}

// inspiration from https://github.com/maxogden/yo-yo/blob/b4e1e8fe2e1081464c1fbdd1ad6c7a0ae7e24ad1/index.js
function copyEvents (fromNode, toNode) {
  const toEventHandlers = Val.cacheElementEventHandlers.get(toNode)
  const fromEventHandlers = Val.cacheElementEventHandlers.get(fromNode)

  // iterate through all event handlers
  uniqueKeys(toEventHandlers, fromEventHandlers).forEach(name => {
    const toEventHandler = toEventHandlers[name]
    const fromEventHandler = fromEventHandlers[name]
    // if existing event handler does not match new event handler
    if (fromEventHandler !== toEventHandler) {
      // if existing event handler is defined
      if (fromEventHandler !== undefined) {
        // remove existing event handler
        fromNode.removeEventListener(name, fromEventHandler)
        delete fromEventHandlers[name]
      }
      // if new event handler is defined
      if (toEventHandler !== undefined) {
        // add new event handler
        fromNode.addEventListener(name, toEventHandler)
        fromEventHandlers[name] = toEventHandler
      }
    }
  })
}

// credit to paolo
// https://github.com/0x00A/TIL/blob/master/javascript/unique-arrays.md
function uniqueKeys (objA = {}, objB = {}) {
  return Array.from(new Set([
    ...Object.keys(objA),
    ...Object.keys(objB)
  ]))
}

### CODE REVIEW

**Comment by treshugart** [comment]
It looks like you only need to get the event handlers for an element, correct? This might be something good to formalise as API. Probably not a good idea to expose the weak map to mutations.

What do you think about exporting a function called `getEventHandlers` instead?

**Comment by treshugart** [comment]
Hey @ahdinosaur, I'm wondering if you had a chance to read my last comment. WDYT?

**Comment by ahdinosaur** [comment]
hey @treshugart. yes, i think you're right. however, i've ended up pulling in this code to [my silly hyperscript module](https://github.com/ahdinosaur/hyps), so no longer depend on `@skatejs/val`. do you still want this pull request or should i close it?

**Comment by treshugart** [comment]
Nah, that's cool, I'll go ahead and close it. Thanks again for the PR, though :)

**Pull request closed without merging**
